# src/report_generator.py
from fpdf import FPDF
from src.models import Company
import datetime

def clean_text(text):

    if not isinstance(text, str):
        return str(text)
        
    # Replacements for common "smart" characters
    replacements = {
        '\u2018': "'", '\u2019': "'", 
        '\u201c': '"', '\u201d': '"', 
        '\u2013': '-', '\u2014': '-', 
        '\u2032': "'", '\u2026': "..."
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
        
    return text.encode('latin-1', 'replace').decode('latin-1')

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'AltScore: Credit Risk Memo', 0, 1, 'C')
        self.line(10, 20, 200, 20)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Generated by AltScore AI | Page {self.page_no()}', 0, 0, 'C')

def generate_pdf(company: Company):
    pdf = PDFReport()
    pdf.add_page()
    
    # --- 1. TITLE & METADATA ---
    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"Target Entity: {clean_text(company.name)}", 0, 1)
    
    pdf.set_font("Arial", "", 10)
    report_date = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
    pdf.cell(0, 6, f"Report Date: {report_date}", 0, 1)
    
    ind = company.industry if company.industry else "Unknown"
    hq = company.headquarters if company.headquarters else "Unknown"
    
    pdf.cell(0, 6, clean_text(f"Industry: {ind} | Age: {company.business_age} Years"), 0, 1)
    pdf.cell(0, 6, clean_text(f"Headquarters: {hq}"), 0, 1)
    pdf.ln(5)
    
    # --- 2. SCORE & DECISION ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Risk Assessment", 0, 1)
    
    score = company.risk_score
    pdf.set_font("Arial", "B", 24)
    if score >= 60:
        pdf.set_text_color(0, 150, 0) # Green
        status = "APPROVE"
    elif score >= 40:
        pdf.set_text_color(200, 150, 0) # Orange
        status = "MANUAL REVIEW"
    else:
        pdf.set_text_color(200, 0, 0) # Red
        status = "REJECT"
        
    pdf.cell(0, 15, f"Score: {score}/100 ({status})", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    # --- 3. PRINCIPAL REASONS ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Principal Reasons for Decision", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    if company.decision_reasons:
        for reason in company.decision_reasons:
            pdf.cell(0, 6, f"- {clean_text(reason)}", 0, 1)
    else:
        pdf.cell(0, 6, "- No critical risk factors identified.", 0, 1)
    pdf.ln(5)

    # --- 4. DETAILED METRICS (NEW! INCLUDES GEO RISK) ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Quantitative Risk Metrics", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    # Row 1
    pdf.cell(95, 6, f"Sentiment Momentum: {company.sentiment_momentum:.3f}", 0, 0)
    pdf.cell(95, 6, f"News Volatility: {company.news_volume_volatility:.3f}", 0, 1)
    
    # Row 2 (Geo Risk)
    pdf.cell(95, 6, f"Geo-Economic Zone: {clean_text(company.geo_risk_label)}", 0, 0)
    pdf.cell(95, 6, f"Legal Flags: {'YES' if company.lawsuit_flag else 'None'}", 0, 1)
    pdf.ln(5)
    
    # --- 5. FINANCIALS ---
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Financial Verification", 0, 1)
    pdf.set_font("Arial", "", 10)
    
    cash_str = f"${company.cash_balance:,.2f}" if company.has_verified_financials else "Unverified"
    pdf.cell(0, 6, f"Verified Cash Balance: {cash_str}", 0, 1)
    
    if company.contagion_penalty > 0:
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 6, f"Contagion Penalty Applied: -{company.contagion_penalty} pts", 0, 1)
        pdf.set_text_color(0, 0, 0)
    else:
        pdf.cell(0, 6, "No contagion penalties applied.", 0, 1)
        
    # --- 6. RELATED ENTITIES ---
    if company.related_entities:
        pdf.ln(2)
        pdf.set_font("Arial", "I", 9)
        pdf.cell(0, 6, "Related Entity Network:", 0, 1)
        for entity in company.related_entities:
            risk = "High Risk" if entity['Risk_Score'] < 50 else "Stable"
            text = f"  * {entity['Name']} ({entity['Relation']}): {risk}"
            pdf.cell(0, 6, clean_text(text), 0, 1)

    return pdf.output(dest='S').encode('latin-1')